/** Demo clinical bills matching Indian Health Insurance Policies in supabase/schema.sql */
export const SAMPLE_BILLS = [
  {
    label: 'Acute Appendectomy (Apollo Hospital)',
    hint: 'Star Gold · Cosmetic scar revision denied',
    category: 'General Surgery',
    patient_id: 'PAT-1001',
    policy_id: '11111111-1111-4111-8111-111111111111',
    diagnosis_code: 'K35.80',
    items: [
      { item_name: 'Room Charges (3 days)', cost: 24000 },
      { item_name: 'Laparoscopic Appendectomy', cost: 85000 },
      { item_name: 'Anesthesia', cost: 18000 },
      { item_name: 'Pre-Op Blood Test Panel', cost: 3500 },
      { item_name: 'Cosmetic Scar Revision Surgery', cost: 32000 },
      { item_name: 'IV Fluids & Antibiotics', cost: 6400 },
      { item_name: 'Vitamin Supplements Pack', cost: 1200 },
    ],
  },
  {
    label: 'Appendectomy Overbilling Check (Apollo Hospital)',
    hint: 'Star Gold · Duplicate, overpriced and unbundled lines flagged',
    category: 'Bill Audit',
    patient_id: 'PAT-1001',
    policy_id: '11111111-1111-4111-8111-111111111111',
    diagnosis_code: 'K35.80',
    items: [
      { item_name: 'Room Charges (3 days)', cost: 24000 },
      { item_name: 'Laparoscopic Appendectomy', cost: 85000 },
      { item_name: 'Anesthesia', cost: 18000 },
      { item_name: 'Anesthesia', cost: 18000 },
      { item_name: 'Abdominal X-Ray', cost: 45000 },
      { item_name: 'Surgical Gloves & Suture Kit', cost: 9500 },
      { item_name: 'Pre-Op Blood Test Panel', cost: 3500 },
    ],
  },
  {
    label: 'Pneumonia Inpatient Stay (Fortis)',
    hint: 'HDFC Silver · 100% clean approval (15% copay)',
    category: 'Pulmonology',
    patient_id: 'PAT-1002',
    policy_id: '22222222-2222-4222-8222-222222222222',
    diagnosis_code: 'J18.9',
    items: [
      { item_name: 'Room Charges (4 days)', cost: 28000 },
      { item_name: 'Pulmonology Consultation', cost: 6500 },
      { item_name: 'Chest X-Ray Digital', cost: 2800 },
      { item_name: 'IV Antibiotics & Nebulization', cost: 32000 },
      { item_name: 'Nursing Care & Oxygen Therapy', cost: 19200 },
    ],
  },
  {
    label: 'Coronary Angioplasty + Stent (Max Heart)',
    hint: 'Care Platinum · 0% copay, gene therapy denied',
    category: 'Cardiology',
    patient_id: 'PAT-1003',
    policy_id: '33333333-3333-4333-8333-333333333333',
    diagnosis_code: 'I21.4',
    items: [
      { item_name: 'Cardiac ICU Charges (2 days)', cost: 65000 },
      { item_name: 'Coronary Angioplasty', cost: 220000 },
      { item_name: 'Drug-Eluting Stent (DES)', cost: 95000 },
      { item_name: 'Cath Lab Facility Charges', cost: 48000 },
      { item_name: 'Cardiology Senior Consultation', cost: 14000 },
      { item_name: 'Experimental Gene Therapy Infusion', cost: 50000 },
    ],
  },
  {
    label: 'TPA Identity Mismatch (Fraud)',
    hint: 'ICICI Basic · Flagged & 100% Denied',
    category: 'Integrity Check',
    patient_id: 'PAT-9999',
    policy_id: '44444444-4444-4444-8444-444444444444',
    diagnosis_code: 'S72.001A',
    items: [
      { item_name: 'Hip Fracture Surgery', cost: 180000 },
      { item_name: 'MRI Scan', cost: 15000 },
      { item_name: 'Room Charges (5 days)', cost: 25000 },
    ],
  },
  {
    label: 'Lymphoma Chemotherapy (Tata Memorial)',
    hint: 'Niva Oncology · Experimental peptides denied',
    category: 'Oncology',
    patient_id: 'PAT-1005',
    policy_id: '55555555-5555-4555-8555-555555555555',
    diagnosis_code: 'C85.90',
    items: [
      { item_name: 'Chemotherapy Infusion Cycle', cost: 145000 },
      { item_name: 'Port-a-Cath Insertion', cost: 38000 },
      { item_name: 'Whole Body PET-CT Scan', cost: 28000 },
      { item_name: 'Oncology Consultation', cost: 12000 },
      { item_name: 'Anti-Emetics & Supportive Care', cost: 9500 },
      { item_name: 'Experimental Off-Label Peptides', cost: 125000 },
      { item_name: 'Ayurvedic Decoction Kit', cost: 27500 },
    ],
  },
  {
    label: 'Total Knee Arthroplasty (Manipal)',
    hint: 'Tata Ortho · Robotic surcharge denied',
    category: 'Orthopedics',
    patient_id: 'PAT-1006',
    policy_id: '66666666-6666-4666-8666-666666666666',
    diagnosis_code: 'M17.11',
    items: [
      { item_name: 'Total Knee Replacement', cost: 250000 },
      { item_name: 'Titanium Prosthesis Implant', cost: 110000 },
      { item_name: 'Spinal Anesthesia', cost: 25000 },
      { item_name: 'Post-Op Physical Therapy', cost: 18000 },
      { item_name: 'Pre-Op Blood Work & X-Ray', cost: 8500 },
      { item_name: 'Robotic-Assisted Surgery Surcharge', cost: 45000 },
      { item_name: 'Private Deluxe Suite Upgrade', cost: 17000 },
    ],
  },
  {
    label: 'Emergency LSCS Delivery (Cloudnine)',
    hint: 'SBI Maternity · Exceeds ₹1.5L policy cap',
    category: 'Obstetrics',
    patient_id: 'PAT-1007',
    policy_id: '77777777-7777-4777-8777-777777777777',
    diagnosis_code: 'O82',
    items: [
      { item_name: 'LSCS Cesarean Section', cost: 85000 },
      { item_name: 'Neonatal Care & Pediatrician', cost: 35000 },
      { item_name: 'Epidural Anesthesia', cost: 18000 },
      { item_name: 'Labor and Delivery Charges', cost: 22000 },
      { item_name: 'Routine Nursery (3 days)', cost: 15000 },
      { item_name: 'Luxury Mother Hamper Pack', cost: 10000 },
    ],
  },
  {
    label: 'DKA Emergency Critical Care (Medanta)',
    hint: 'Bajaj Critical · 100% clean approval (5% copay)',
    category: 'Critical Care',
    patient_id: 'PAT-1008',
    policy_id: '88888888-8888-4888-8888-888888888888',
    diagnosis_code: 'E10.10',
    items: [
      { item_name: 'Emergency Room Care', cost: 15000 },
      { item_name: 'ICU Charges (3 days)', cost: 75000 },
      { item_name: 'Critical Care Consultation', cost: 25000 },
      { item_name: 'Continuous IV Insulin Infusion', cost: 38000 },
      { item_name: 'Arterial Blood Gas Analysis', cost: 18500 },
      { item_name: 'Electrolyte Monitoring Panel', cost: 16500 },
      { item_name: 'Cardiac Monitoring & IV Fluids', cost: 30000 },
    ],
  },
  {
    label: 'Cholecystectomy Conflict (Narayana Health)',
    hint: 'New India · Laparoscopic + Open duplicate',
    category: 'General Surgery',
    patient_id: 'PAT-1009',
    policy_id: '99999999-9999-4999-8999-999999999999',
    diagnosis_code: 'K80.20',
    items: [
      { item_name: 'Laparoscopic Cholecystectomy', cost: 75000 },
      { item_name: 'Anesthesia', cost: 18000 },
      { item_name: 'Operation Theater Charges', cost: 35000 },
      { item_name: 'Pre-Op Lab Work & Ultrasound', cost: 12000 },
      { item_name: 'Open Cholecystectomy Duplicate Billing', cost: 58000 },
    ],
  },
  {
    label: 'RTA Head Trauma & Neuro-HDU (AIIMS)',
    hint: 'Oriental Trauma · 100% covered emergency',
    category: 'Trauma / Neuro',
    patient_id: 'PAT-1010',
    policy_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    diagnosis_code: 'S06.0X0A',
    items: [
      { item_name: 'Emergency Trauma Resuscitation', cost: 35000 },
      { item_name: 'Brain CT Scan with Contrast', cost: 14500 },
      { item_name: 'High Dependency Unit (HDU) (3 days)', cost: 78000 },
      { item_name: 'Neurotrauma Consultation', cost: 18000 },
      { item_name: 'Cervical Spine X-Ray', cost: 6500 },
      { item_name: 'Osmotic Diuretics Infusion', cost: 12000 },
      { item_name: 'Suture and Wound Debridement', cost: 14000 },
      { item_name: 'Tetanus Prophylaxis', cost: 500 },
    ],
  },
  {
    label: 'Dengue with Platelet Transfusion (Ganga Ram)',
    hint: 'National Vector · Papaya extract denied',
    category: 'Infectious Disease',
    patient_id: 'PAT-1011',
    policy_id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    diagnosis_code: 'A91',
    items: [
      { item_name: 'Isolation Ward Bed (4 days)', cost: 32000 },
      { item_name: 'Single Donor Platelet Apheresis', cost: 34000 },
      { item_name: 'Complete Blood Count Monitoring', cost: 8500 },
      { item_name: 'NS1 Dengue Antigen & IgM Serology', cost: 4500 },
      { item_name: 'Infectious Disease Consultation', cost: 6500 },
      { item_name: 'Caripill Herbal Papaya Extract Supplements', cost: 3500 },
      { item_name: 'Air Purifier Rental', cost: 12000 },
    ],
  },
  {
    label: 'Kidney Stone Laser Lithotripsy (PM-JAY)',
    hint: 'Ayushman Bharat · 100% Cashless Package',
    category: 'Urology',
    patient_id: 'PAT-1012',
    policy_id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    diagnosis_code: 'N20.1',
    items: [
      { item_name: 'URS Laser Lithotripsy', cost: 45000 },
      { item_name: 'Spinal Anesthesia', cost: 9000 },
      { item_name: 'Ultrasound KUB', cost: 3500 },
      { item_name: 'Pre-Op Blood & Urine Examination', cost: 4500 },
      { item_name: 'Post-Op Stent Removal', cost: 6000 },
    ],
  },
];
