/** Demo scenarios matched to the seeded mock policies in supabase/schema.sql */
export const SAMPLE_BILLS = [
  {
    label: 'Appendectomy + cosmetic add-on',
    hint: 'Gold · expect PARTIAL',
    category: 'General Surgery',
    patient_id: 'PAT-1001',
    policy_id: '11111111-1111-4111-8111-111111111111',
    diagnosis_code: 'K35.80',
    items: [
      { item_name: 'Room Charges (3 days)', cost: 1800 },
      { item_name: 'Laparoscopic Appendectomy', cost: 8500 },
      { item_name: 'Anesthesia', cost: 1200 },
      { item_name: 'Blood Test Panel', cost: 350 },
      { item_name: 'Cosmetic Scar Revision Surgery', cost: 3200 },
      { item_name: 'IV Fluids & Medications', cost: 640 },
      { item_name: 'Vitamin Supplements Pack', cost: 90 },
    ],
  },
  {
    label: 'Clean pneumonia admission',
    hint: 'Silver · expect APPROVED',
    category: 'Pulmonology',
    patient_id: 'PAT-1002',
    policy_id: '22222222-2222-4222-8222-222222222222',
    diagnosis_code: 'J18.9',
    items: [
      { item_name: 'Room Charges (4 days)', cost: 2000 },
      { item_name: 'Pulmonologist Consultation', cost: 450 },
      { item_name: 'Chest X-Ray', cost: 300 },
      { item_name: 'Antibiotic Medications', cost: 780 },
      { item_name: 'Nursing Care', cost: 600 },
    ],
  },
  {
    label: 'Cardiac stent, high value',
    hint: 'Platinum · 0% copay',
    category: 'Cardiology',
    patient_id: 'PAT-1003',
    policy_id: '33333333-3333-4333-8333-333333333333',
    diagnosis_code: 'I21.4',
    items: [
      { item_name: 'ICU Charges (2 days)', cost: 6000 },
      { item_name: 'Coronary Angioplasty', cost: 24000 },
      { item_name: 'Drug-Eluting Stent', cost: 9500 },
      { item_name: 'Cardiology Consultation', cost: 700 },
      { item_name: 'Experimental Gene Therapy Infusion', cost: 15000 },
      { item_name: 'Ambulance Transfer', cost: 450 },
    ],
  },
  {
    label: 'Mismatched patient (fraud)',
    hint: 'Basic · expect DENIED',
    category: 'Integrity Check',
    patient_id: 'PAT-9999',
    policy_id: '44444444-4444-4444-8444-444444444444',
    diagnosis_code: 'S72.001A',
    items: [
      { item_name: 'Hip Fracture Surgery', cost: 18000 },
      { item_name: 'MRI Scan', cost: 1500 },
      { item_name: 'Room Charges (5 days)', cost: 2500 },
    ],
  },
  {
    label: 'Lymphoma Oncology Chemotherapy',
    hint: 'Oncology · experimental drug denied',
    category: 'Oncology',
    patient_id: 'PAT-1005',
    policy_id: '55555555-5555-4555-8555-555555555555',
    diagnosis_code: 'C85.90',
    items: [
      { item_name: 'Chemotherapy Infusion', cost: 18500 },
      { item_name: 'Port-a-Cath Insertion', cost: 4200 },
      { item_name: 'PET Scan', cost: 3800 },
      { item_name: 'Oncology Consultation', cost: 650 },
      { item_name: 'Anti-Emetics', cost: 420 },
      { item_name: 'Blood Transfusion', cost: 1100 },
      { item_name: 'Experimental Off-Label Drugs', cost: 12000 },
      { item_name: 'Alternative Herbal Therapy', cost: 1500 },
    ],
  },
  {
    label: 'Total Knee Replacement Arthroplasty',
    hint: 'Ortho-Plus · robotic surcharge denied',
    category: 'Orthopedics',
    patient_id: 'PAT-1006',
    policy_id: '66666666-6666-4666-8666-666666666666',
    diagnosis_code: 'M17.11',
    items: [
      { item_name: 'Total Knee Replacement', cost: 28000 },
      { item_name: 'Titanium Prosthesis Implant', cost: 14500 },
      { item_name: 'Spinal Anesthesia', cost: 2800 },
      { item_name: 'Post-Op Physical Therapy', cost: 1600 },
      { item_name: 'Pre-Op Blood Work', cost: 450 },
      { item_name: 'Crutches and Walker', cost: 280 },
      { item_name: 'Robotic-Assisted Surgery Surcharge', cost: 6500 },
      { item_name: 'Private Deluxe Suite', cost: 3200 },
    ],
  },
  {
    label: 'Cesarean Delivery & Neonatal Care',
    hint: 'Maternity · exceeds policy cap',
    category: 'Obstetrics',
    patient_id: 'PAT-1007',
    policy_id: '77777777-7777-4777-8777-777777777777',
    diagnosis_code: 'O82',
    items: [
      { item_name: 'Labor and Delivery', cost: 12000 },
      { item_name: 'Cesarean Section', cost: 22000 },
      { item_name: 'Obstetrician Consultation', cost: 1800 },
      { item_name: 'Epidural Anesthesia', cost: 3200 },
      { item_name: 'Neonatal Care', cost: 8500 },
      { item_name: 'Newborn Blood Screening', cost: 650 },
      { item_name: 'Routine Nursery', cost: 4500 },
      { item_name: 'Luxury Amenities Pack', cost: 2800 },
    ],
  },
  {
    label: 'Diabetic Ketoacidosis Emergency ICU',
    hint: 'Comprehensive · 100% clean approved',
    category: 'Critical Care',
    patient_id: 'PAT-1008',
    policy_id: '88888888-8888-4888-8888-888888888888',
    diagnosis_code: 'E10.10',
    items: [
      { item_name: 'Emergency Room Care', cost: 2500 },
      { item_name: 'ICU Charges', cost: 12000 },
      { item_name: 'Critical Care Consultation', cost: 1800 },
      { item_name: 'Continuous IV Insulin Infusion', cost: 3400 },
      { item_name: 'Arterial Blood Gas Analysis', cost: 950 },
      { item_name: 'Electrolyte Panel', cost: 620 },
      { item_name: 'Cardiac Monitoring', cost: 1200 },
      { item_name: 'IV Fluids and Resuscitation', cost: 880 },
    ],
  },
  {
    label: 'Cholecystectomy Duplicate Billing',
    hint: 'Standard · mutual surgical conflict',
    category: 'General Surgery',
    patient_id: 'PAT-1009',
    policy_id: '99999999-9999-4999-8999-999999999999',
    diagnosis_code: 'K80.20',
    items: [
      { item_name: 'Laparoscopic Cholecystectomy', cost: 7500 },
      { item_name: 'Anesthesia', cost: 1400 },
      { item_name: 'Operating Room Facility', cost: 3200 },
      { item_name: 'Pre-Op Lab Work', cost: 480 },
      { item_name: 'Antibiotics & Analgesics', cost: 650 },
      { item_name: 'Open Cholecystectomy Duplicate Billing', cost: 8900 },
      { item_name: 'Unbundled Surgical Trays', cost: 1200 },
    ],
  },
  {
    label: 'Head Trauma & HDU Observation',
    hint: 'Trauma · clean inpatient emergency',
    category: 'Trauma / Neuro',
    patient_id: 'PAT-1010',
    policy_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    diagnosis_code: 'S06.0X0A',
    items: [
      { item_name: 'Emergency Trauma Resuscitation', cost: 4500 },
      { item_name: 'Brain CT Scan with Contrast', cost: 1850 },
      { item_name: 'High Dependency Unit (HDU)', cost: 5200 },
      { item_name: 'Neurotrauma Consultation', cost: 1100 },
      { item_name: 'Cervical Spine X-Ray', cost: 650 },
      { item_name: 'Osmotic Diuretics Infusion', cost: 720 },
      { item_name: 'Suture and Wound Debridement', cost: 980 },
      { item_name: 'Tetanus Prophylaxis', cost: 150 },
    ],
  },
];
